/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package turismo;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marmota
 */
public class GraphServer extends javax.swing.JFrame {

    /**
     * Creates new form GraphServer
     */ServidorServo main;
    Passagem p;
    Hospedagem h;
    
    public GraphServer(ServidorServo ss) {
        initComponents();
        main = ss;
        this.setVisible(true);
        System.out.println("potato");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Make = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        Destination = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Departure = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        verify = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        makeLodging = new javax.swing.JButton();
        removeLodging = new javax.swing.JButton();
        verify2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Make.setText("Criar");
        Make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeActionPerformed(evt);
            }
        });

        jLabel1.setText("Origem/Cidade:");

        jLabel5.setText("Quantidade:");

        jLabel2.setText("Destino/Hotel:");

        quantity.setText("2");

        day.setText("10");

        price.setText("10");

        Destination.setText("Tokyo");

        jLabel3.setText("Preço:");

        jLabel4.setText("Data de Ida:");

        Departure.setText("Curitiba");

        year.setText("10");

        month.setText("10");

        verify.setText("Verify");
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });

        Remove.setText("Remover");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        makeLodging.setText("Criar Hospadagem");
        makeLodging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeLodgingActionPerformed(evt);
            }
        });

        removeLodging.setText("Remover Hospedagem");
        removeLodging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLodgingActionPerformed(evt);
            }
        });

        verify2.setText("Verify2");
        verify2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Make)
                        .addGap(18, 18, 18)
                        .addComponent(Remove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verify)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(makeLodging)
                        .addGap(18, 18, 18)
                        .addComponent(removeLodging)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verify2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Departure, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                .addComponent(Destination)
                                .addComponent(price, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Departure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeLodging)
                    .addComponent(removeLodging)
                    .addComponent(verify2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Make)
                    .addComponent(verify)
                    .addComponent(Remove))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeActionPerformed

        System.out.println(Departure.getText() + Integer.parseInt(quantity.getText()) + Float.parseFloat(price.getText()));
        
        p = new Passagem(Departure.getText(), Destination.getText(), day.getText(), month.getText(), year.getText(), Integer.parseInt(quantity.getText()), Integer.parseInt(price.getText()));
        try {
            main.addAirfare(p);
        } catch (RemoteException ex) {
            Logger.getLogger(GraphServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MakeActionPerformed

    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed
        try {
            main.verify(day.getText() + month.getText() + year.getText());
        } catch (RemoteException ex) {
            Logger.getLogger(GraphServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_verifyActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        
        p = new Passagem(Departure.getText(), Destination.getText(), day.getText(), month.getText(), year.getText(), Integer.parseInt(quantity.getText()), Integer.parseInt(price.getText()));
        try {
            main.removeAirfare(p);
        } catch (RemoteException ex) {
            Logger.getLogger(GraphServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RemoveActionPerformed

    private void verify2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify2ActionPerformed
        try {
            main.verifyLodging(day.getText() + month.getText() + year.getText());
        } catch (RemoteException ex) {
            Logger.getLogger(GraphServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_verify2ActionPerformed

    private void removeLodgingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLodgingActionPerformed
        h = new Hospedagem(Departure.getText(), Destination.getText(), day.getText(), month.getText(), year.getText(), day.getText(), month.getText(), year.getText(), Integer.parseInt(quantity.getText()), (Integer.parseInt(price.getText())));
        try {
            main.removeLodging(h);
        } catch (RemoteException ex) {
            Logger.getLogger(GraphServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_removeLodgingActionPerformed

    private void makeLodgingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeLodgingActionPerformed
        System.out.println(Departure.getText() + Integer.parseInt(quantity.getText()) + Float.parseFloat(price.getText()));
        
        h = new Hospedagem(Departure.getText(), Destination.getText(), day.getText(), month.getText(), year.getText(), day.getText(), month.getText(), year.getText(), Integer.parseInt(quantity.getText()), Integer.parseInt(price.getText()));
        try {
            main.addLodging(h);
        } catch (RemoteException ex) {
            Logger.getLogger(GraphServer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_makeLodgingActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Departure;
    private javax.swing.JTextField Destination;
    private javax.swing.JButton Make;
    private javax.swing.JButton Remove;
    private javax.swing.JTextField day;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton makeLodging;
    private javax.swing.JTextField month;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton removeLodging;
    private javax.swing.JButton verify;
    private javax.swing.JButton verify2;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
